### ISSUE TITLE
Documentation is not consistent with code

### ISSUE THREAD

**Issue by maches** [Wynd-Lab/nihilus-symfony-resolver#5]
## Expected Behavior
Provided configuration for node `nihilus_cqrs.query` and for `nihilus_cqrs.command` will be consistent in other parts of it.
## Current Behavior
In a real project I got
```  In ArrayNode.php line 303:                                                                         
                                                                                                     
    Unrecognized option "middlewares" under "nihilus_cqrs.query"    
```

## Possible Solution
Make it consistent

## Steps to Reproduce

What we have in docs:
**middleware.md:**
```yaml
nihilus_cqrs:
    query|command:
        middleware:
            main_chain: ['transaction']
            chain_name: ['@main_chain', 'another_middleware']
```

**README.md**
```yaml
nihilus_cqrs:
  query:
    middlewares:
      global: ['test1']
      transaction: ['@global', 'test2']
    binding:
      Nihilus\CQRSBundle\Tests\App\CQRS\Query\Handler\TestQuery: ['@transaction', 'test3']
  command:
    middlewares: ~
    binding: ~
```
In code:
https://github.com/Wynd-Lab/nihilus-symfony-resolver/blob/master/src/DependencyInjection/Configuration.php#L29
```php
    const CHAINS_OF_MIDDLEWARE = 'middleware_chains';
```

## Context

Symfony container is corrupted by generated yaml config file

## Your Environment

* Version used: 1.0.0
* Operating System and version: Archlinux (version is not meaningful)
* Link to your project: Wynd monolith Ewok (1.24)
